sudo: required

language: node_js
node_js:
  - "8"

services:
  - docker

before_install:
  - echo "rct stands for „Rasa client tester“"
  - docker build -f test.Dockerfile -t rct .
  - docker run -d -p 127.0.0.1:5005:5005 --name rct rct
  - docker logs -f rct &
  - travis_wait 3 sleep 180

script:
  - npm i
  - npm test